gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#c94c16"
      - "bold"
    inactiveBorderColor:
      - "#664c00"
    searchingActiveBorderColor:
      - "#c94c16"
      - "bold"
    optionsTextColor:
      - "#268bd3"
    selectedLineBgColor:
      - "#1a6397"
    cherryPickedCommitFgColor:
      - "#268bd3"
    cherryPickedCommitBgColor:
      - "#d23681"
    markedBaseCommitFgColor:
      - "#268bd3"
    markedBaseCommitBgColor:
      - "#b28500"
    unstagedChangesColor:
      - "#f55350"
    defaultFgColor:
      - "#839395"
git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
  allBranchesLogCmds:
    - git log --graph --color=always --date=relative --pretty=format:'%Cgreen%h %Creset%cd %Cblue[%cn] %Creset%s%C(yellow)%d%C(reset)' --all --
  branchLogCmd: git log --graph --color=always --date=relative --pretty=format:'%Cgreen%h %Creset%cd %Cblue[%cn] %Creset%s%C(yellow)%d%C(reset)' {{branchName}} --
